# any logged-in user authenticated through the
# console needs READONLY access to these resources
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: console-extensions-reader
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
rules:
- apiGroups:
  - console.openshift.io
  resources:
  - consolelinks
  - consolenotifications
  - consoleexternalloglinks
  - consoleclidownloads
  - consoleyamlsamples
  - consolequickstarts
  - consoleplugins
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: project-helm-chartrepository-editor
  labels:
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
rules:
- apiGroups:
  - helm.openshift.io
  resources:
  - projecthelmchartrepositories
  verbs:
  - get
  - list
  - update
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: project-helm-chartrepository-admin
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
rules:
- apiGroups:
  - helm.openshift.io
  resources:
  - projecthelmchartrepositories
  verbs:
  - get
  - list
  - update
  - create
  - delete
  - patch
  - watch


